sudo: required
language: python
cache: pip
dist: xenial
python:
  - 3.6
  - 3.7
install:
  - python setup.py develop
  - pip install flake8
script:
  - python setup.py test
  - python -m flake8 squabble
