language: python
cache: pip
python:
  - "3.6"
  - "3.7"
install:
  - python setup.py develop
  - pip install pytest
script:
  - python -m pytest -v tests squabble --doctest-modules --disable-warnings
