sudo: required
language: python
cache: pip
dist: xenial
python:
  - 3.6
  - 3.7
install:
  - python setup.py develop
  - pip install pytest pytest-cov flake8
script:
  - python -m pytest -v tests squabble --doctest-modules --disable-warnings --cov=squabble
  - python -m flake8 squabble
